extends: _common.yaml
experiment_name: poly_b0

data:
  task: binary

model:
  backbone: efficientnet_b0
  head:
    type: linear
    out_dim: 2

loss:
  type: poly
  poly_eps: 2.0
  class_weights: auto
  label_smoothing: 0.05

train:
  epochs: 30
  use_two_view: false
  sampler: random
